config/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from rest_framework import routers
# apps API Viewsets imports
from gis.apps.serials.api.viewsets import SerialNumberAPIViewset
from gis.apps.deadlines.api.viewsets import DeadlineAPIViewset
from gis.apps.applications.api.viewsets import ApplicationAPIViewset

router = routers.DefaultRouter()
# api router url confs
router.register('serial_numbers', SerialNumberAPIViewset, base_name='serial_number')
router.register('applications', ApplicationAPIViewset, base_name='application')
router.register('deadlines', DeadlineAPIViewset, base_name='deadline')

# app imports
from .views import HomePageView, NewsPageView, ContactPageView

urlpatterns = [
    # static pages
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^contact/', ContactPageView.as_view(), name='contact'),
    url(r'^news/', NewsPageView.as_view(), name='news'),
    # app url confs
    url(r'^serial/', include('gis.apps.serials.urls', namespace='serials')),
    url(r'^application/', include('gis.apps.applications.urls', namespace='apply')),
    url(r'^deadline/', include('gis.apps.deadlines.urls', namespace='deadline')),

    # api
    url(r'^api/', include(router.urls, namespace='api')),
    # admin
    url(r'^admin/', admin.site.urls),
    # authentication
    url(r'^accounts/', include('registration.backends.default.urls')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gis/apps/applications/urls.py
from django.conf.urls import url
from .views import (
    ProfileView,
    ApplicationListView,
    AllListView,
    CertListView,
    DiplomaListView,
    HNDListView,
    DegreeListView,
    MastersListView,
    OthersListView,
    SummaryView,
    ProfileUpdateView,
)

urlpatterns = [
    url(r'^$', ApplicationListView.as_view(), name='list'),
    url(r'^dashboard/application-list/all/$', AllListView.as_view(), name='all_list'),
    url(r'^dashboard/application-list/certificate/$', CertListView.as_view(), name='cert_list'),
    url(r'^dashboard/application-list/diploma/$', DiplomaListView.as_view(), name='diploma_list'),
    url(r'^dashboard/application-list/hnd/$', HNDListView.as_view(), name='hnd_list'),
    url(r'^dashboard/application-list/degree/$', DegreeListView.as_view(), name='degree_list'),
    url(r'^dashboard/application-list/masters/$', MastersListView.as_view(), name='masters_list'),
    url(r'^dashboard/application-list/others/$', OthersListView.as_view(), name='others_list'),
    url(r'^profile/(?P<pk>\d+)/$', ProfileView.as_view(), name='details'),
    url(r'^profile/(?P<pk>\d+)/summary/$', SummaryView.as_view(), name='summary'),
    url(r'^(?P<pk>\d+)/update/$', ProfileUpdateView.as_view(), name='update'),
]

gis/apps/deadlines/urls.py
from django.conf.urls import url
from .views import (
    DeadlineCreateView,
    DeadlineDeleteView,
    DeadlineListView,
    DeadlineUpdateView,
)

urlpatterns = [
    url(r'^$', DeadlineListView.as_view(), name="list"),
    url(r'^add-new/$', DeadlineCreateView.as_view(), name="create"),
    url(r'^(?P<pk>\d+)/update/$', DeadlineUpdateView.as_view(), name="update"),
    url(r'^(?P<pk>\d+)/delete/$', DeadlineDeleteView.as_view(), name="delete")
]

gis/apps/deadlines/models.py
from django.db import models


class DeadlineDate(models.Model):
    user = models.ForeignKey('auth.User', default=1, on_delete=models.CASCADE)
    deadline = models.DateField()
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return str(self.deadline)

gis/apps/deadlines/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy
from django.views.generic import UpdateView, CreateView, ListView, DeleteView
from datetime import date

# from this App (i.e the Serials App)
from .models import DeadlineDate


from braces.views import LoginRequiredMixin, StaffuserRequiredMixin, SuperuserRequiredMixin

class DeadlineListView(LoginRequiredMixin, StaffuserRequiredMixin, ListView):
    model = DeadlineDate
    queryset = DeadlineDate.objects.all().order_by('-timestamp')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_header"] = "List of INACTIVE Serial Numbers"
        return context


class DeadlineCreateView(LoginRequiredMixin, StaffuserRequiredMixin, CreateView):
    model = DeadlineDate
    fields = ['deadline']
    success_url = reverse_lazy("deadline:list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "Create Deadline" 
        context["page_header"] = "create Deadline"
        context["button_text"] = "Create"
        return context
    

class DeadlineUpdateView(LoginRequiredMixin, StaffuserRequiredMixin, UpdateView):
    model = DeadlineDate
    fields = ['deadline']
    success_url = reverse_lazy("deadline:list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "Update Deadline" 
        context["page_header"] = "Update Deadline"
        context["button_text"] = "Update"
        return context


class DeadlineDeleteView(LoginRequiredMixin, SuperuserRequiredMixin,DeleteView):
    model = DeadlineDate
    success_url = reverse_lazy("deadline:list")

gis/apps/deadlines/templates/deadlines/deadlinedate_confirm_delete.html
{% load static %}
{% load crispy_forms_tags %}
<!doctype>
<html>
    <head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="">

<title>{{page_title}}</title>
         <!-- Bootstrap core CSS -->
    <!-- <link href="../../dist/css/bootstrap.min.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href="{% static 'static/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- <img src="{% static "my_app/myexample.jpg" %}" alt="My image"/> -->
    <!-- Custom styles for this template -->
    <!-- <link href="navbar-static-top.css" rel="stylesheet"> -->
    <link href="{% static 'static/css/navbar-static-top.css' %}" rel="stylesheet">
     <link href="{% static 'static/css/custom.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
    -->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    </head>
    <body>
           <!-- Static navbar -->

    <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">GIS</a>
              </div>
              <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                  <li><a href="{% url 'home' %}">Home</a></li>
                  <li><a href="{% url 'news' %}">News</a></li>
                  <li><a href="{% url 'contact' %}">Contact</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'apply:list' %}"><i class="glyphicon glyphicon-user"></i> {{request.user}}</a></li>
                  <li><a href="{% url 'auth_logout' %}">Logout</a></li>
                  {% endif %}

                  {% if request.user.is_authenticated and request.user.is_staff %}
                  <li><a href="{% url 'apply:all_list' %}">Applications</a></li>
                  <li><a href="{% url 'serials:list' %}">Serials</a></li>
                  <li><a href="{% url 'deadline:list' %}">Deadlines</a></li>
            {% endif %}
                </ul>
              </div><!--/.nav-collapse -->
            </div>
          </nav>

<section>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
       <h1>Are You Sure You Want to Delete {{object}}?</h1>
       <form method="POST" action="">
            {% csrf_token %}
            <input type="submit" value="Yes Delete" class="btn btn-danger">
            <a class="btn btn-primary" href="{% url 'deadline:list' %}">View Deadline</a>
       </form>
</div>
</div>
</section>

    </body>
</html>

gis/apps/deadlines/templates/deadlines/deadlinedate_form.html
{% load static %}
{% load crispy_forms_tags %}
<!doctype>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">
    
    <title>{{page_title}}</title>
             <!-- Bootstrap core CSS -->
        <!-- <link href="../../dist/css/bootstrap.min.css" rel="stylesheet"> -->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
        <link href="{% static 'static/css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- <img src="{% static "my_app/myexample.jpg" %}" alt="My image"/> -->
        <!-- Custom styles for this template -->
        <!-- <link href="navbar-static-top.css" rel="stylesheet"> -->
        <link href="{% static 'static/css/navbar-static-top.css' %}" rel="stylesheet">
         <link href="{% static 'static/css/custom.css' %}" rel="stylesheet">
    
        <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
        <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]
        <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
        -->
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        </head>
    <body>
           <!-- Static navbar -->

    <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">GIS</a>
              </div>
              <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                  <li><a href="{% url 'home' %}">Home</a></li>
                  <li><a href="{% url 'news' %}">News</a></li>
                  <li><a href="{% url 'contact' %}">Contact</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'apply:list' %}"><i class="glyphicon glyphicon-user"></i> {{request.user}}</a></li>
                  <li><a href="{% url 'auth_logout' %}">Logout</a></li>
                  {% endif %}

                  {% if request.user.is_authenticated and request.user.is_staff %}
                  <li><a href="{% url 'apply:all_list' %}">Applications</a></li>
                  <li><a href="{% url 'serials:list' %}">Serials</a></li>
                  <li><a href="{% url 'deadline:list' %}">Deadlines</a></li>
            {% endif %}
                </ul>
              </div><!--/.nav-collapse -->
            </div>
          </nav>

<section>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
         <h1>{{page_header}}</h1>
         <form action="" method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="{{button_text}}">
         </form>
</div>
</div>
</section>

    </body>
</html>

gis/apps/deadlines/templates/deadlines/deadlinedate_list.html
{% load static %}
{% load crispy_forms_tags %}
<!doctype>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">
    
    <title>{{page_title}}</title>
             <!-- Bootstrap core CSS -->
        <!-- <link href="../../dist/css/bootstrap.min.css" rel="stylesheet"> -->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
        <link href="{% static 'static/css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- <img src="{% static "my_app/myexample.jpg" %}" alt="My image"/> -->
        <!-- Custom styles for this template -->
        <!-- <link href="navbar-static-top.css" rel="stylesheet"> -->
        <link href="{% static 'static/css/navbar-static-top.css' %}" rel="stylesheet">
         <link href="{% static 'static/css/custom.css' %}" rel="stylesheet">
    
        <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
        <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]
        <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
        -->
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        </head>
    <body>
           <!-- Static navbar -->

    <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">GIS</a>
              </div>
              <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                  <li><a href="{% url 'home' %}">Home</a></li>
                  <li><a href="{% url 'news' %}">News</a></li>
                  <li><a href="{% url 'contact' %}">Contact</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'apply:list' %}"><i class="glyphicon glyphicon-user"></i> {{request.user}}</a></li>
                  <li><a href="{% url 'auth_logout' %}">Logout</a></li>
                  {% endif %}

                  {% if request.user.is_authenticated and request.user.is_staff %}
                  <li><a href="{% url 'apply:all_list' %}">Applications</a></li>
                  <li><a href="{% url 'serials:list' %}">Serials</a></li>
                  <li><a href="{% url 'deadline:list' %}">Deadlines</a></li>
            {% endif %}
                </ul>
              </div><!--/.nav-collapse -->
            </div>
          </nav>

<section>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center text-info">{{page_header}}</h1>
        <table class="table table-responsive table-hover table-bordered">
        <thead>
            <tr>
            <th>Deadline Date</th> <th>Timestamp</th>
            </tr>
        </thead>
        <tbody>
            {% for d in object_list %}
            <tr>
            <td>{{d.deadline}}</td>
            <td>{{d.timestamp}}</td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
        <br/>
        <div>
        <a class="btn btn-primary" href="{% url 'deadline:create' %}">
            <i class="fa fa-plus"></i>New Deadline</a>
        </div>
</div>
</div>
</section>

    </body>
</html>