config/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from rest_framework import routers
# apps API Viewsets imports
from gis.apps.serials.api.viewsets import SerialNumberAPIViewset
from gis.apps.deadlines.api.viewsets import DeadlineAPIViewset
from gis.apps.applications.api.viewsets import ApplicationAPIViewset

router = routers.DefaultRouter()
# api router url confs
router.register('serial_numbers', SerialNumberAPIViewset, base_name='serial_number')
router.register('applications', ApplicationAPIViewset, base_name='application')
router.register('deadlines', DeadlineAPIViewset, base_name='deadline')

# app imports
from .views import HomePageView, NewsPageView, ContactPageView

urlpatterns = [
    # static pages
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^contact/', ContactPageView.as_view(), name='contact'),
    url(r'^news/', NewsPageView.as_view(), name='news'),
    # app url confs
    url(r'^serial/', include('gis.apps.serials.urls', namespace='serials')),
    url(r'^application/', include('gis.apps.applications.urls', namespace='apply')),
    url(r'^deadline/', include('gis.apps.deadlines.urls', namespace='deadline')),

    # api
    url(r'^api/', include(router.urls, namespace='api')),
    # admin
    url(r'^admin/', admin.site.urls),
    # authentication
    url(r'^accounts/', include('registration.backends.default.urls')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gis/apps/applications/urls.py
from django.conf.urls import url
from .views import (
    ProfileView,
    ApplicationListView,
    AllListView,
    CertListView,
    DiplomaListView,
    HNDListView,
    DegreeListView,
    MastersListView,
    OthersListView,
    SummaryView,
    ProfileUpdateView,
)

urlpatterns = [
    url(r'^$', ApplicationListView.as_view(), name='list'),
    url(r'^dashboard/application-list/all/$', AllListView.as_view(), name='all_list'),
    url(r'^dashboard/application-list/certificate/$', CertListView.as_view(), name='cert_list'),
    url(r'^dashboard/application-list/diploma/$', DiplomaListView.as_view(), name='diploma_list'),
    url(r'^dashboard/application-list/hnd/$', HNDListView.as_view(), name='hnd_list'),
    url(r'^dashboard/application-list/degree/$', DegreeListView.as_view(), name='degree_list'),
    url(r'^dashboard/application-list/masters/$', MastersListView.as_view(), name='masters_list'),
    url(r'^dashboard/application-list/others/$', OthersListView.as_view(), name='others_list'),
    url(r'^profile/(?P<pk>\d+)/$', ProfileView.as_view(), name='details'),
    url(r'^profile/(?P<pk>\d+)/summary/$', SummaryView.as_view(), name='summary'),
    url(r'^(?P<pk>\d+)/update/$', ProfileUpdateView.as_view(), name='update'),
]

gis/apps/serials/urls.py
from django.conf.urls import url
from .views import (
    serials_view,
    SerialsCreateView,
    SerialsUpdateView,
    ActiveSerialsListView,
    AllSerialsListView,
    InactiveSerialsListView,
    SerialsDeleteView,
)

urlpatterns = [
    url(r'^$', serials_view, name="serial_link"),
    url(r'^all/$', AllSerialsListView.as_view(), name="list"),
    url(r'^active/$', ActiveSerialsListView.as_view(), name="active-list"),
    url(r'^inactive/$', InactiveSerialsListView.as_view(), name="inactive-list"),
    url(r'^generate/$', SerialsCreateView.as_view(), name="create"),
    url(r'^(?P<pk>\d+)/update/$', SerialsUpdateView.as_view(), name="update"),
    url(r'^(?P<pk>\d+)/delete/$', SerialsDeleteView.as_view(), name="delete")
]

gis/apps/serials/models.py
from django.db import models
from django.conf import settings
import random
import string

class Serials(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    serial_number = models.CharField(max_length=25, blank=True, null=True)
    STATUS_OPTIONS = (
        ("ACT", "ACTIVE"),
        ("IN", "INACTIVE")
    )
    status = models.CharField(max_length=3, choices=STATUS_OPTIONS, default="ACT")
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return str(self.serial_number)

    def get_serial_number(self):
        return ''.join(random.choice(string.ascii_uppercase + string.ascii_lowercase + string.digits) for _ in range(25))

    def save(self, *args, **kwargs):
        if not self.serial_number:
            self.serial_number = self.get_serial_number()
        super().save()

gis/apps/serials/forms.py
from django import forms
from .models import Serials


class SerialNumberForm(forms.ModelForm):
    serial_number = forms.CharField(widget=forms.TextInput(attrs={'autocomplete': 'off'}), max_length=25)

    class Meta:
        fields = ['serial_number']
        model = Serials


class SerialsGenerateForm(forms.ModelForm):
    class Meta:
        model = Serials
        fields = ['user', 'status']


class SerialsUpdateForm(forms.ModelForm):
    serial_number = forms.CharField(max_length=25, widget=forms.TextInput({"autocomplete":"off"}), required=True)

    class Meta:
        model = Serials
        fields = ['serial_number', 'status']

gis/apps/serials/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy
from django.views.generic import UpdateView, CreateView, ListView, DeleteView
from datetime import date

# from this App (i.e the Serials App)
from .models import Serials
from .forms import SerialNumberForm, SerialsUpdateForm, SerialsGenerateForm

# from Another App (i.e Application App)
from gis.apps.applications.models import Application

from braces.views import LoginRequiredMixin, StaffuserRequiredMixin, SuperuserRequiredMixin


def serials_view(request):
    # redirects to login page if not logged in
    if not request.user.is_authenticated():
        return redirect('auth_login')
    form = SerialNumberForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        # checking if d serial is valid and no user has it in use.
        if Serials.objects.all().filter(serial_number=instance.serial_number) and not Application.objects.all().filter(serial_number=instance.serial_number):
            # creates a new application for the use if the serial number is not wrong or not in use
            Application.objects.create(
                user=request.user,
                serial_number=instance.serial_number,
                date_of_birth = date.today(),
                date_completed = date.today()
            )
            return redirect('apply:list')
        # checks to see if we already created the applicaton for the current user
        elif Application.objects.all().filter(user=request.user, serial_number=instance.serial_number):
            return redirect('apply:list')
        # checks to prevent multiple use of serial number
        elif Serials.objects.filter(serial_number=instance.serial_number) and Application.objects.all().filter(serial_number=instance.serial_number):
            return HttpResponse("<h1> OOPS!! Serial Number is In Use</h1>")
        # checks to prevent the use of invalid serial number
        elif not Serials.objects.all().filter(serial_number=instance.serial_number):
            return HttpResponse("<h1> OOPSS!! Wrong Serial Number,Try Again</h1>")

    context = {
        'form': form,
    }

    return render(request, 'serials/index.html', context)


class AllSerialsListView(LoginRequiredMixin, StaffuserRequiredMixin, ListView):
    model = Serials
    queryset = Serials.objects.all().order_by('-updated_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_header"] = "List of All Serial Numbers"
        return context


class ActiveSerialsListView(LoginRequiredMixin, StaffuserRequiredMixin, ListView):
    model = Serials
    queryset = Serials.objects.filter(status="ACT").order_by('-updated_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_header"] = "List of ACTIVE Serial Numbers"
        return context


class InactiveSerialsListView(LoginRequiredMixin, StaffuserRequiredMixin, ListView):
    model = Serials
    queryset = Serials.objects.filter(status="IN").order_by('-updated_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_header"] = "List of INACTIVE Serial Numbers"
        return context


class SerialsCreateView(LoginRequiredMixin, StaffuserRequiredMixin, CreateView):
    model = Serials
    fields = ['status']
    success_url = reverse_lazy("serials:list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(SerialsCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "Generate Serial" 
        context["page_header"] = "Generate A Serial Number"
        context["button_text"] = "Generate"
        return context
    

class SerialsUpdateView(LoginRequiredMixin, StaffuserRequiredMixin, UpdateView):
    model = Serials
    form_class = SerialsUpdateForm
    success_url = reverse_lazy("serials:list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "Update Serial" 
        context["page_header"] = "Update Serial Number"
        context["button_text"] = "Update"
        return context


class SerialsDeleteView(LoginRequiredMixin, SuperuserRequiredMixin,DeleteView):
    model = Serials
    success_url = reverse_lazy("serials:list")

gis/apps/serials/templates/serials/index.html
{% load staticfiles %}
{% load crispy_forms_tags %}
<!doctype>
<html>
    <head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="">

<title>Serial Number</title>
         <!-- Bootstrap core CSS -->
    <!-- <link href="../../dist/css/bootstrap.min.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href="{% static 'static/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- <img src="{% static "my_app/myexample.jpg" %}" alt="My image"/> -->
    <!-- Custom styles for this template -->
    <!-- <link href="navbar-static-top.css" rel="stylesheet"> -->
    <link href="{% static 'static/css/navbar-static-top.css' %}" rel="stylesheet">
     <link href="{% static 'static/css/custom.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
    -->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    </head>
    <body>
           <!-- Static navbar -->
    
    <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">GIS</a>
              </div>
              <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                  <li><a href="{% url 'home' %}">Home</a></li>
                  <li><a href="{% url 'news' %}">News</a></li>
                  <li><a href="{% url 'contact' %}">Contact</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                <li><a href="#"><i class="glyphicon glyphicon-user"></i> {{request.user}}</a></li>
                  <li><a href="{% url 'auth_logout' %}">Logout</a></li>
                  {% endif %}

                  {% if request.user.is_authenticated and request.user.is_staff %}
                  <li><a href="{% url 'apply:all_list' %}">Applications</a></li>
                  <li><a href="{% url 'serials:list' %}">Serials</a></li>
                  <li><a href="{% url 'deadline:list' %}">Deadlines</a></li>
            {% endif %}
                </ul>
              </div><!--/.nav-collapse -->
            </div>
          </nav>

<section>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
<h1 class="text-info text-center">SERIAL NUMBER</h1>
<form method="POST" action="">
{% csrf_token %}
{{form|crispy}}
<input type="submit" value="Submit" class="btn btn-success btn-block"/>
</form>
</div>
</div>
</section>
        
    </body>
</html>

gis/apps/serials/templates/serials/serials_confirm_delete.html
{% load static %}
{% load crispy_forms_tags %}
<!doctype>
<html>
    <head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="">

<title>{{page_title}}</title>
         <!-- Bootstrap core CSS -->
    <!-- <link href="../../dist/css/bootstrap.min.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href="{% static 'static/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- <img src="{% static "my_app/myexample.jpg" %}" alt="My image"/> -->
    <!-- Custom styles for this template -->
    <!-- <link href="navbar-static-top.css" rel="stylesheet"> -->
    <link href="{% static 'static/css/navbar-static-top.css' %}" rel="stylesheet">
     <link href="{% static 'static/css/custom.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
    -->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    </head>
    <body>
           <!-- Static navbar -->

    <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">GIS</a>
              </div>
              <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                  <li><a href="{% url 'home' %}">Home</a></li>
                  <li><a href="{% url 'news' %}">News</a></li>
                  <li><a href="{% url 'contact' %}">Contact</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'apply:list' %}"><i class="glyphicon glyphicon-user"></i> {{request.user}}</a></li>
                  <li><a href="{% url 'auth_logout' %}">Logout</a></li>
                  {% endif %}

                  {% if request.user.is_authenticated and request.user.is_staff %}
                  <li><a href="{% url 'apply:all_list' %}">Applications</a></li>
                  <li><a href="{% url 'serials:list' %}">Serials</a></li>
                  <li><a href="{% url 'deadline:list' %}">Deadlines</a></li>
            {% endif %}
                </ul>
              </div><!--/.nav-collapse -->
            </div>
          </nav>

<section>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
       <h1>Are You Sure You Want to Delete {{object}}?</h1>
       <form method="POST" action="">
            {% csrf_token %}
            <input type="submit" value="Yes Delete" class="btn btn-danger">
            <a class="btn btn-primary" href="{% url 'serials:list' %}">View Serials</a>
       </form>
</div>
</div>
</section>

    </body>
</html>

gis/apps/serials/templates/serials/serials_form.html
{% load static %}
{% load crispy_forms_tags %}
<!doctype>
<html>
    <head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="">

<title>{{page_title}}</title>
         <!-- Bootstrap core CSS -->
    <!-- <link href="../../dist/css/bootstrap.min.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href="{% static 'static/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- <img src="{% static "my_app/myexample.jpg" %}" alt="My image"/> -->
    <!-- Custom styles for this template -->
    <!-- <link href="navbar-static-top.css" rel="stylesheet"> -->
    <link href="{% static 'static/css/navbar-static-top.css' %}" rel="stylesheet">
     <link href="{% static 'static/css/custom.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
    -->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    </head>
    <body>
           <!-- Static navbar -->

    <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">GIS</a>
              </div>
              <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                  <li><a href="{% url 'home' %}">Home</a></li>
                  <li><a href="{% url 'news' %}">News</a></li>
                  <li><a href="{% url 'contact' %}">Contact</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'apply:list' %}"><i class="glyphicon glyphicon-user"></i> {{request.user}}</a></li>
                  <li><a href="{% url 'auth_logout' %}">Logout</a></li>
                  {% endif %}

                  {% if request.user.is_authenticated and request.user.is_staff %}
                  <li><a href="{% url 'apply:all_list' %}">Applications</a></li>
                  <li><a href="{% url 'serials:list' %}">Serials</a></li>
                  <li><a href="{% url 'deadline:list' %}">Deadlines</a></li>
            {% endif %}
                </ul>
              </div><!--/.nav-collapse -->
            </div>
          </nav>

<section>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
         <h1>{{page_header}}</h1>
         <form action="" method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="{{button_text}}">
         </form>
</div>
</div>
</section>

    </body>
</html>

gis/apps/serials/templates/serials/serials_list.html
{% load static %}
{% load crispy_forms_tags %}
<!doctype>
<html>
    <head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="">

<title>{{page_title}}</title>
         <!-- Bootstrap core CSS -->
    <!-- <link href="../../dist/css/bootstrap.min.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href="{% static 'static/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- <img src="{% static "my_app/myexample.jpg" %}" alt="My image"/> -->
    <!-- Custom styles for this template -->
    <!-- <link href="navbar-static-top.css" rel="stylesheet"> -->
    <link href="{% static 'static/css/navbar-static-top.css' %}" rel="stylesheet">
     <link href="{% static 'static/css/custom.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
    -->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    </head>
    <body>
           <!-- Static navbar -->

    <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">GIS</a>
              </div>
              <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                  <li><a href="{% url 'home' %}">Home</a></li>
                  <li><a href="{% url 'news' %}">News</a></li>
                  <li><a href="{% url 'contact' %}">Contact</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'apply:list' %}"><i class="glyphicon glyphicon-user"></i> {{request.user}}</a></li>
                  <li><a href="{% url 'auth_logout' %}">Logout</a></li>
                  {% endif %}

                  {% if request.user.is_authenticated and request.user.is_staff %}
                  <li><a href="{% url 'apply:all_list' %}">Applications</a></li>
                  <li><a href="{% url 'serials:list' %}">Serials</a></li>
                  <li><a href="{% url 'deadline:list' %}">Deadlines</a></li>
            {% endif %}
                </ul>
              </div><!--/.nav-collapse -->
            </div>
          </nav>

<section>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center text-info">{{page_header}}</h1>
        <table class="table table-responsive table-hover table-bordered">
        <thead>
            <tr>
            <th>Admin</th> <th>Serial Number</th> <th>Created At</th> <th>Updated At</th>
            <th colspan="2">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for serial in object_list %}
            <tr>
            <td>{{serial.user.username}}</td>
            <td class="text-info">
           {{serial.serial_number}}
            </td>
            <td>{{serial.created_at}}</td>
            <td>{{serial.updated_at}}</td>
            <td class="text-success">
            <a href="{% url 'serials:update' pk=serial.id %}">Update</a>
        </td>
            <td class="text-danger">
            <a href="{% url 'serials:delete' pk=serial.id %}">Delete</a>
        </td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
        <br/>
        <div>
        <a class="btn btn-primary" href="{% url 'serials:create' %}">
            <i class="fa fa-plus"></i>Add Serial</a>
        <a class="btn btn-primary" href="{% url 'serials:list' %}">All Serials</a>
        <a class="btn btn-primary" href="{% url 'serials:active-list' %}">Active Serials</a>
        <a class="btn btn-primary" href="{% url 'serials:inactive-list' %}">Inctive Serials</a>
        </div>
</div>
</div>
</section>

    </body>
</html>