config/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from rest_framework import routers
# apps API Viewsets imports
from gis.apps.serials.api.viewsets import SerialNumberAPIViewset
from gis.apps.deadlines.api.viewsets import DeadlineAPIViewset
from gis.apps.applications.api.viewsets import ApplicationAPIViewset

router = routers.DefaultRouter()
# api router url confs
router.register('serial_numbers', SerialNumberAPIViewset, base_name='serial_number')
router.register('applications', ApplicationAPIViewset, base_name='application')
router.register('deadlines', DeadlineAPIViewset, base_name='deadline')

# app imports
from .views import HomePageView, NewsPageView, ContactPageView

urlpatterns = [
    # static pages
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^contact/', ContactPageView.as_view(), name='contact'),
    url(r'^news/', NewsPageView.as_view(), name='news'),
    # app url confs
    url(r'^serial/', include('gis.apps.serials.urls', namespace='serials')),
    url(r'^application/', include('gis.apps.applications.urls', namespace='apply')),
    url(r'^deadline/', include('gis.apps.deadlines.urls', namespace='deadline')),

    # api
    url(r'^api/', include(router.urls, namespace='api')),
    # admin
    url(r'^admin/', admin.site.urls),
    # authentication
    url(r'^accounts/', include('registration.backends.default.urls')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gis/apps/applications/urls.py
from django.conf.urls import url
from .views import (
    ProfileView,
    ApplicationListView,
    AllListView,
    CertListView,
    DiplomaListView,
    HNDListView,
    DegreeListView,
    MastersListView,
    OthersListView,
    SummaryView,
    ProfileUpdateView,
)

urlpatterns = [
    url(r'^$', ApplicationListView.as_view(), name='list'),
    url(r'^dashboard/application-list/all/$', AllListView.as_view(), name='all_list'),
    url(r'^dashboard/application-list/certificate/$', CertListView.as_view(), name='cert_list'),
    url(r'^dashboard/application-list/diploma/$', DiplomaListView.as_view(), name='diploma_list'),
    url(r'^dashboard/application-list/hnd/$', HNDListView.as_view(), name='hnd_list'),
    url(r'^dashboard/application-list/degree/$', DegreeListView.as_view(), name='degree_list'),
    url(r'^dashboard/application-list/masters/$', MastersListView.as_view(), name='masters_list'),
    url(r'^dashboard/application-list/others/$', OthersListView.as_view(), name='others_list'),
    url(r'^profile/(?P<pk>\d+)/$', ProfileView.as_view(), name='details'),
    url(r'^profile/(?P<pk>\d+)/summary/$', SummaryView.as_view(), name='summary'),
    url(r'^(?P<pk>\d+)/update/$', ProfileUpdateView.as_view(), name='update'),
]

gis/apps/applications/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse

from .validators import validate_file_extension


def upload_location(instance, filename):
    return "%s/%s" % (instance.user.username, filename)


class Application(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, default=0, on_delete=models.CASCADE)
    image_width = models.IntegerField(default=0)
    image_height = models.IntegerField(default=0)
    image = models.ImageField(width_field='image_width', height_field='image_height', upload_to=upload_location)

    email = models.EmailField()
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    other_names = models.CharField(max_length=60, null=True, blank=True)
    gender_choices = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    gender = models.CharField(max_length=1, choices=gender_choices)
    date_of_birth = models.DateField(auto_now=False, auto_now_add=False)
    nationality = models.CharField(max_length=60)
    phone = models.CharField(max_length=15)
    address = models.TextField(max_length=200)
    city = models.CharField(max_length=60)
    country = models.CharField(max_length=60)
    birth_certificate = models.FileField(upload_to=upload_location, validators=[validate_file_extension])

    # Education Status
    QUALIFICATION_OPTIONS = (
        ('CERT', 'SSCE/WASSCE'),
        ('DIP', 'Diploma'),
        ('HND', 'Higher National Diploma (HND)'),
        ('DEG', 'Degree'),
        ('MAST', 'Masters Degree'),
        ('OTH', 'Other')
    )
    highest_qualification = models.CharField(max_length=4, choices=QUALIFICATION_OPTIONS)
    specify_qualification = models.CharField(max_length=120, null=True, blank=True)
    name_of_institution = models.CharField(max_length=250)
    course_studied = models.CharField(max_length=200)
    date_completed = models.DateField(auto_now=False, auto_now_add=False)
    educational_certificate = models.FileField(upload_to=upload_location, validators=[validate_file_extension])
    certificate_number = models.CharField(max_length=250)

    # Parent or Guadian Info
    guardian_full_name = models.CharField(max_length=250)
    guardian_phone = models.CharField(max_length=15)
    guardian_address = models.TextField(max_length=200)
    guardian_email = models.EmailField()
    relationship_to_guardian = models.CharField(max_length=50)

    # access count for admin management
    access_count = models.IntegerField(default=0)
    applied_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField(auto_now=True, auto_now_add=False)

    # checkfield options
    ts_and_cs = models.BooleanField(default=False)

    # user's serial number
    serial_number = models.CharField(max_length=25, unique=True)

    def __str__(self):
        return self.last_name

    def get_absolute_url(self):
        return reverse('apply:details', kwargs={'pk': self.pk})

gis/apps/applications/forms.py
from django import forms

#model imports
from .models import Application


class ApplicationForm(forms.ModelForm):
    date_of_birth = forms.DateField(widget=forms.SelectDateWidget(years=[
        '1991',
        '1992',
        '1993',
        '1994',
        '1995',
        '1996',
        '1997',
        '1998',
        '1999',
        '2000'
    ]))
    date_completed = forms.DateField(widget=forms.SelectDateWidget(years=[
        '2000',
        '2001',
        '2002',
        '2003',
        '2004',
        '2005',
        '2006',
        '2007',
        '2008',
        '2009',
        '2010',
        '2011',
        '2012',
        '2013',
        '2014',
        '2015',
        '2016',
        '2017',
        '2018'
    ]))
    other_names = forms.CharField(required=False)
    specify_qualification = forms.CharField(
        label="if 'Other', specify",
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'if you chose Other above, specify'})
        )
    birth_certificate = forms.FileField(label='Birth Certificate (.pdf)')
    educational_certificate = forms.FileField(label='Educational Certificate (.pdf)')
    access_count = forms.IntegerField(required=False, widget=forms.HiddenInput())
    ts_and_cs = forms.BooleanField(required=True, label='Accept Terms and Conditions')

    class Meta:
        model = Application
        fields = [
            'image',
            'last_name',
            'first_name',
            'other_names',
            'gender',
            'date_of_birth',
            'nationality',
            'birth_certificate',
            'email',
            'phone',
            'address',
            'city',
            'highest_qualification',
            'specify_qualification',
            'name_of_institution',
            'course_studied',
            'date_completed',
            'educational_certificate',
            'certificate_number',
            'guardian_full_name',
            'guardian_phone',
            'guardian_address',
            'guardian_email',
            'relationship_to_guardian',
            'ts_and_cs',
            'access_count'
        ]


class UserSerialNumberForm(forms.ModelForm):
    class Meta:
        fields = ['serial_number']
        model = Application

gis/apps/applications/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.conf import settings
from django.core.urlresolvers import reverse, reverse_lazy
from datetime import date
from django.views.generic import ListView, DetailView, UpdateView
from braces.views import StaffuserRequiredMixin
from .mixins import ProfileUpdateRedirectsMixin, ProfileRedirectsMixin, ListRedirectsMixin

# models and forms import
from .models import Application
from .forms import ApplicationForm
from gis.apps.deadlines.models import DeadlineDate


class AllListView(StaffuserRequiredMixin, ListView):
    model = Application
    template_name = 'apply/all_list.html'

    def get_context_data(self, **kwargs):
        context = super(AllListView, self).get_context_data(**kwargs)
        context['body_title'] = "LISTS OF <b>ALL</b> APPLICANTS WITH VARIOUS QUALIFICATIONS"
        return context


class CertListView(StaffuserRequiredMixin, ListView):
    model = Application
    template_name = 'apply/all_list.html'

    def get_queryset(self):
        return Application.objects.all().filter(highest_qualification='CERT')

    def get_context_data(self, **kwargs):
        context = super(CertListView, self).get_context_data(**kwargs)
        context['body_title'] = "LISTS OF ALL APPLICANTS WITH <b>SSCE/WASSCE</b> QUALIFICATION"
        return context


class DiplomaListView(StaffuserRequiredMixin, ListView):
    model = Application
    template_name = 'apply/all_list.html'

    def get_queryset(self):
        return Application.objects.all().filter(highest_qualification='DIP')

    def get_context_data(self, **kwargs):
        context = super(DiplomaListView, self).get_context_data(**kwargs)
        context['body_title'] = "LISTS OF ALL APPLICANTS WITH <b>DIPLOMA</b> QUALIFICATION"
        return context


class HNDListView(StaffuserRequiredMixin, ListView):
    model = Application
    template_name = 'apply/all_list.html'

    def get_queryset(self):
        return Application.objects.all().filter(highest_qualification='HND')

    def get_context_data(self, **kwargs):
        context = super(HNDListView, self).get_context_data(**kwargs)
        context['body_title'] = "LISTS OF ALL APPLICANTS WITH <b>Higher National Diploma (HND)</b> QUALIFICATION"
        return context


class DegreeListView(StaffuserRequiredMixin, ListView):
    model = Application
    template_name = 'apply/all_list.html'

    def get_queryset(self):
        return Application.objects.all().filter(highest_qualification='DEG')

    def get_context_data(self, **kwargs):
        context = super(DegreeListView, self).get_context_data(**kwargs)
        context['body_title'] = "LISTS OF ALL APPLICANTS WITH <b>DEGREE</b> QUALIFICATION"
        return context


class MastersListView(StaffuserRequiredMixin, ListView):
    model = Application
    template_name = 'apply/all_list.html'

    def get_queryset(self):
        return Application.objects.all().filter(highest_qualification='MAST')

    def get_context_data(self, **kwargs):
        context = super(MastersListView, self).get_context_data(**kwargs)
        context['body_title'] = "LISTS OF ALL APPLICANTS WITH <b>MASTERS DEGREE</b> QUALIFICATION"
        return context


class OthersListView(StaffuserRequiredMixin, ListView):
    model = Application
    template_name = 'apply/all_list.html'

    def get_queryset(self):
        return Application.objects.all().filter(highest_qualification='OTH')

    def get_context_data(self, **kwargs):
        context = super(OthersListView, self).get_context_data(**kwargs)
        context['body_title'] = "LISTS OF ALL APPLICANTS WITH <b>Specified OR Other</b> QUALIFICATIONS"
        return context


# lists all the applications submitted so far for a superuser. and own application for a none superuser
class ApplicationListView(ListRedirectsMixin, ListView):
    model = Application
    template_name = 'apply/index.html'

    def get_queryset(self):
        if self.request.user.is_staff or self.request.user.is_superuser:
            return Application.objects.all().order_by('-applied_at')
        else:
            return Application.objects.all().filter(user=self.request.user)


# shows the profile summary of the applicant
class ProfileView(ProfileRedirectsMixin, DetailView):
    model = Application
    template_name = 'apply/profile.html'

    def get_context_data(self, **kwargs):
        # instance = get_object_or_404(Application, pk=self.object.pk)
        context = super(ProfileView, self).get_context_data(**kwargs)
        context['visits_left'] = 3-self.object.access_count
        return context


# updates the applicationn information of the user
class ProfileUpdateView(ProfileUpdateRedirectsMixin, UpdateView):
    model = Application
    template_name = 'apply/update.html'
    form_class = ApplicationForm

    def get_success_url(self):
        return reverse_lazy('apply:details', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super(ProfileUpdateView, self).get_context_data(**kwargs)
        context['todays_date'] = date.today()
        context['deadline'] = DeadlineDate.objects.all().latest('timestamp')
        return context

    def form_valid(self, form):
        form.instance.access_count += 1
        return super(ProfileUpdateView, self).form_valid(form)


class SummaryView(DetailView):
    model = Application
    template_name = 'apply/summary.html'

gis/apps/applications/templates/apply/all_list.html
{% load staticfiles %}
{% load crispy_forms_tags %}
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">
    
    <title>{{page_title}}</title>
             <!-- Bootstrap core CSS -->
        <!-- <link href="../../dist/css/bootstrap.min.css" rel="stylesheet"> -->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
        <link href="{% static 'static/css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- <img src="{% static "my_app/myexample.jpg" %}" alt="My image"/> -->
        <!-- Custom styles for this template -->
        <!-- <link href="navbar-static-top.css" rel="stylesheet"> -->
        <link href="{% static 'static/css/navbar-static-top.css' %}" rel="stylesheet">
         <link href="{% static 'static/css/custom.css' %}" rel="stylesheet">
    
        <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
        <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]
        <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
        -->
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        </head>
    <body>
           <!-- Static navbar -->

    <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">GIS</a>
              </div>
              <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                  <li><a href="{% url 'apply:all_list' %}">ALL Applicants</a></li>
                  <li><a href="{% url 'apply:cert_list' %}">SSCE/WASSCE</a></li>
                  <li><a href="{% url 'apply:diploma_list' %}">DIPLOMA</a></li>
                  <li><a href="{% url 'apply:hnd_list' %}">HND</a></li>
                  <li><a href="{% url 'apply:degree_list' %}">DEGREE</a></li>
                  <li><a href="{% url 'apply:masters_list' %}">MASTERS</a></li>
                  <li><a href="{% url 'apply:others_list' %}">OTHERS</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'apply:list' %}"><i class="glyphicon glyphicon-user"></i> {{request.user}}</a></li>
                  <li><a href="{% url 'auth_logout' %}">Logout</a></li>
                  {% endif %}

                  {% if request.user.is_authenticated and request.user.is_staff %}
                  <li><a href="{% url 'apply:all_list' %}">Applications</a></li>
                  <li><a href="{% url 'serials:list' %}">Serials</a></li>
                  <li><a href="{% url 'deadline:list' %}">Deadlines</a></li>
            {% endif %}
                </ul>
              </div><!--/.nav-collapse -->
            </div>
          </nav>

<section>
  <div class="row">
      <div class="col-md-10 col-md-offset-1">
            <h3 class="text-center text-info">{{body_title|safe}}</h3> <hr>
          <table class="table table-responsive table-hover">
              <thead>
              <tr class="text-info">
                  <th>Full Name</th> <th>Qualification</th> <th>Date of Birth</th> <th>Gender</th> <th>Nationality</th>
              </tr>
              </thead>

              <tbody>
              {% for instance in object_list %}
              <tr>
                  <th><a href="{{instance.get_absolute_url}}">{{instance.last_name}}, {{instance.first_name}} {{instance.other_names}}</a> </th>
                  <td>{{instance.highest_qualification}}</td> <td>{{instance.date_of_birth}}</td>
                  <td>{{instance.gender}}</td> <td>{{instance.nationality}}</td>
              </tr>
              {% empty %}
              <h3>No Applicants Yet</h3>
              {% endfor %}
              </tbody>
          </table>
      </div>
      </div>
</section>


</body>
</html>

gis/apps/applications/templates/apply/index.html
{% load staticfiles %}
{% load crispy_forms_tags %}
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">
    
    <title>{{page_title}}</title>
             <!-- Bootstrap core CSS -->
        <!-- <link href="../../dist/css/bootstrap.min.css" rel="stylesheet"> -->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
        <link href="{% static 'static/css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- <img src="{% static "my_app/myexample.jpg" %}" alt="My image"/> -->
        <!-- Custom styles for this template -->
        <!-- <link href="navbar-static-top.css" rel="stylesheet"> -->
        <link href="{% static 'static/css/navbar-static-top.css' %}" rel="stylesheet">
         <link href="{% static 'static/css/custom.css' %}" rel="stylesheet">
    
        <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
        <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]
        <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
        -->
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        </head>
    <body>
           <!-- Static navbar -->

    <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">GIS</a>
              </div>
              <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                  <li><a href="{% url 'home' %}">Home</a></li>
                  <li><a href="{% url 'news' %}">News</a></li>
                  <li><a href="{% url 'contact' %}">Contact</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'apply:list' %}"><i class="glyphicon glyphicon-user"></i> {{request.user}}</a></li>
                  <li><a href="{% url 'auth_logout' %}">Logout</a></li>
                  {% endif %}

                  {% if request.user.is_authenticated and request.user.is_staff %}
                  <li><a href="{% url 'apply:all_list' %}">Applications</a></li>
                  <li><a href="{% url 'serials:list' %}">Serials</a></li>
                  <li><a href="{% url 'deadline:list' %}">Deadlines</a></li>
            {% endif %}
                </ul>
              </div><!--/.nav-collapse -->
            </div>
          </nav>

<section>
<h1 class="text-center text-info">WELCOME {{request.user|upper}}</h1>
{% for inst in object_list %}
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">

        <div class="thumbnail">
            {% if inst.image %}
            <img src="{{inst.image.url}}" class="img-responsive" style="max-height:300px; max-width:300px;"/>
            {% endif %}
            <div class="caption">
{% if inst.first_name %} <p>Name: {{inst.first_name}} {{inst.last_name}} {{inst.other_names}}</p> {% endif %}
                <p>Serial No: {{inst.serial_number}}</p>
                <span><a href="{{ inst.get_absolute_url }}" class="btn btn-primary">View Info >></a></span>
            </div>
        </div>
    </div>
</div>
<br/> <br/>
        {% endfor %}
</section>
</body>
</html>

gis/apps/applications/templates/apply/profile.html
{% load staticfiles %}
{% load crispy_forms_tags %}
<!doctype>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">
    
    <title>{{page_title}}</title>
             <!-- Bootstrap core CSS -->
        <!-- <link href="../../dist/css/bootstrap.min.css" rel="stylesheet"> -->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
        <link href="{% static 'static/css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- <img src="{% static "my_app/myexample.jpg" %}" alt="My image"/> -->
        <!-- Custom styles for this template -->
        <!-- <link href="navbar-static-top.css" rel="stylesheet"> -->
        <link href="{% static 'static/css/navbar-static-top.css' %}" rel="stylesheet">
         <link href="{% static 'static/css/custom.css' %}" rel="stylesheet">
    
        <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
        <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]
        <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
        -->
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        </head>
    <body>
           <!-- Static navbar -->

    <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">GIS</a>
              </div>
              <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                  <li><a href="{% url 'home' %}">Home</a></li>
                  <li><a href="{% url 'news' %}">News</a></li>
                  <li><a href="{% url 'contact' %}">Contact</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'apply:list' %}"><i class="glyphicon glyphicon-user"></i> {{request.user}}</a></li>
                  <li><a href="{% url 'auth_logout' %}">Logout</a></li>
                  {% endif %}

                  {% if request.user.is_authenticated and request.user.is_staff %}
                  <li><a href="{% url 'apply:all_list' %}">Applications</a></li>
                  <li><a href="{% url 'serials:list' %}">Serials</a></li>
                  <li><a href="{% url 'deadline:list' %}">Deadlines</a></li>
            {% endif %}
                </ul>
              </div><!--/.nav-collapse -->
            </div>
          </nav>

<section>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <h1 class="text-info">Application Information (Profile)</h1>
        <small class="text-warning"><b>You Have {{visits_left}} more Chances to Edit Your Information</b></small>
      </span>
        <br/><br/><br/>
        <div class="row">
        <div class="col-lg-4 col-lg-offset-4">
          {% if object.image %}
          <img src="{{object.image.url}}" style="max-height:200px; max-width:150px;"/>
          {% endif %}
        </div>
      </div>
        <br/>
{% if object.first_name %}
Name: {{object.first_name}} {{object.last_name}} {{object.other_names}}
{% else %}
Username: {{object.user.username}}
{% endif %} <br/>
Gender: {{object.gender}} <br/>
Date Of Birth: {{object.date_of_birth}}<br/>
Nationality: {{object.nationality}}<br/>
Your Email: {{object.email}}<br/>
Phone #: {{object.phone}}<br/>
Address: {{object.address}}<br/>
City: {{object.city}}<br/>
<hr>
<br/>
<h3>EDUCATIONAL INFORMATION</h3>
Qualification Certificate: {{object.highest_qualification}}<br/>
Institution Completed: {{object.name_of_institution}}<br/>
Course Studied: {{object.course_studied}}<br/>
Date of Completion: {{object.date_completed}}<br/>
Certificate Number: {{object.certificate_number}}<br/>
<hr>
<br/>
<h3>PARENT OF GUARDIAN INFORMATION</h3>
Guardian's FullName: {{object.guardian_full_name}}<br/>
Guardian's Phone #: {{object.guardian_phone}}<br/>
Guardian's Address: {{object.guardian_address}}<br/>
Guardian's Email: {{object.guardian_email}}<br/>
Relationship to Guardian: {{object.relationship_to_guardian}}<br/>
<hr>
<br/>
Serial Number: {{object.serial_number}}
<br/> <br/>

{% if object.access_count is 0 %}
  <a href="{% url 'apply:update' pk=object.pk %}" class="btn btn-primary btn-block">Fill Form >></a>
{% else %}
  <a href="{% url 'apply:summary' pk=object.pk %}" class="btn btn-success">View Summary</a>
  <a href="{% url 'apply:update' pk=object.pk %}" class="btn btn-primary">Update Info >></a>
{% endif %}
<br/> <br/>
</div>
</div>
</section>

    </body>
</html>